### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by diemol** [zalando/zalenium#654]
This issue has been created to collect all the feature requests written in different other issues, which are technically possible and we just need help from the community to implement them.

If you are interested in helping us, just comment below with the feature you want to help with, and we will be happy to guide you through the process of implementing and testing it.

All related issues are closed for now. When someone starts working on one of the feature requests, we will reopen it and discuss development over there.

- [ ] [Feature] Change video file extension, in desiredCapabilities #202 
  * Produce videos with smaller sizes
- [ ] [Feature] Integrate https://github.com/butomo1989/docker-android to Zalenium #217 
  * Spin the Android emulator from Zalenium and collect videos + logs
- [x] [feature] Auto-cleanup the dashboard #274 -> Implemented by @ecktom in #713 
- [x] Dashboard - pass search text as parameter in the URL #284 -> Implemented by @takeya0x86 in #767 
- [x] [feature] Loading spinner and refresh for cleanup #306 -> Implemented by @ecktom in #713
- [ ] SSL Support #407
- [ ] Feature Request: Update Live Preview without refreshing page #423
- [ ] Question re: shared volume for node (not hub) video file writing #445
  * Instead of copying files from containers/pods to the Hub, mount the directories in all containers/pods to avoid the extra task to copy the files.
- [ ] Ability to start and stop video recording from the tests. #490
- [x] We are using Cross Browser Testing - 3rd Party could provider for browsers #524 -> Implemented by @daphnemcrossbrowser in #898
- [ ] Check Sauce Labs usage quota before doing additional requests #649 
- [ ] Ability to start selenium pods using a different node selector to what is defined in the Zalenium manifest #662
- [ ] Custom annotations on the created Nodes/Pods #727 
- [ ] run multiple docker images, using different browser versions #809 #923
- [ ] Zalenium High-Availability/Cluster Kubernetes Mode #484
- [ ] Automate Helm Chart Geneation #917
- [ ] Setting maxTestSessions to 0 should disable node shutdown  #933
- [ ] Enhance tests to verify tunnel for cloud providers is working #945
- [x] LambdaTest support #947
- [ ] Be able to configure http proxy for reaching browserstack #979

**Comment by tborys** [comment]
Hi guys,

This comment is related to: **Ability to start selenium pods using a different node selector to what is defined in the Zalenium manifest #662**

I've got a similar issue to the one stated in #662 but I believe the use case is slightly different. 

We run our VM instances on openstack which uses cinder as representation of our storage resources. Unfortunately cinder does not support ReadWriteMany Acces Mode, so if we want to claim available storage it's based on first come first served pod and rest of the pods are trying to bind themselves without luck.

I've noticed however that once the videos are finished they are available on the zalenium hub. My theory was to add node selector to the hub and assign it to particular node. This way I could claim storage only for that particular pod. Turns out that all the pods are starting on that labelled node which limits kubernetes scalability feature to node resources. 

It sounds that ideal solution is to be able to assign zalenium hub pod to specific node and let the rest of selenium pods to spin on any node as kubernetes allows them to. 

Do you guys have any suggestions on how to go about this? 
Would feedback provided [here](https://github.com/zalando/zalenium/issues/662#issuecomment-406918857): by @pearj be sufficient enough?
Any suggiestions welcome!

Cheers

**Comment by ywangii** [comment]
Hi, I am curious if Zalenium has/will have the feature to pass down the permission to other cloud provider, e.g. Saucelabs when redirect the request. 

Our issue is we configured the Zalenium container with the correct permission to access the internal network, but when it redirects the request to Saucelabs and trigger a job with it, it is unable to access the internal network due to lacking of permissions. 

If not, is there a way for us to contribute this feature if it's doable? Appreciate any suggestions or thoughts on it!

**Comment by diemol** [comment]
> Hi, I am curious if Zalenium has/will have the feature to pass down the permission to other cloud provider, e.g. Saucelabs when redirect the request.
> 
> Our issue is we configured the Zalenium container with the correct permission to access the internal network, but when it redirects the request to Saucelabs and trigger a job with it, it is unable to access the internal network due to lacking of permissions.
> 
> If not, is there a way for us to contribute this feature if it's doable? Appreciate any suggestions or thoughts on it!

What operating system? It might be a docker limitation, e.g. it is known that it does not work in OSX.

**Comment by ywangii** [comment]
> > Hi, I am curious if Zalenium has/will have the feature to pass down the permission to other cloud provider, e.g. Saucelabs when redirect the request.
> > Our issue is we configured the Zalenium container with the correct permission to access the internal network, but when it redirects the request to Saucelabs and trigger a job with it, it is unable to access the internal network due to lacking of permissions.
> > If not, is there a way for us to contribute this feature if it's doable? Appreciate any suggestions or thoughts on it!
> 
> What operating system? It might be a docker limitation, e.g. it is known that it does not work in OSX.

Hi, thanks for the reply and sorry I didnt explain the issue very clearly. I was saying when Zalenium redirects the req to Saucelabs, its Saucelabs that does not have the correct permission for internal network access (not Zalenium if this makes confusion). My guess is Zalenium might not support creating the tunnel for Saucelabs with the proper permission for internal network access?

**Comment by gregorygold** [comment]
Hello all,
I was trying to use the Zalenium to do the GeoIP testing, basically via Winderproxy.
They do have a solution to use Saucelabs with Winderproxy via tunnel connection to proxy locations, so we could pretend that the browser opens in other geolocation, but I have not seen and example for usage with Zalenum.
Does anyone have an answer?

**Comment by diemol** [comment]
Closing this one since Zalenium is not under development anymore. No more features will be added.
